### ISSUE TITLE
Created a task list for GSOC'24

### ISSUE THREAD

**Issue by dhruvmehtaaa** [dhruvmehtaaa/ZOO-Project#1]
# Task List GSOC'24
# Advancing the ZOO-Project testing capabilities

- [x] **Setup Environment:**
   - [x] Set up development environment.
   - [x] Install necessary dependencies.

- [x] **Identify Key Capabilities:**
   - [x] Analyze core functionalities of ZOO-Project.
   - [x] Prioritize capabilities for testing.

- [ ] **Implement Core Tests:**
   - [ ] Write unit tests for basic functionality.
